### ISSUE TITLE
Move to using Color/Safe over just color

### ISSUE THREAD

**Issue by Faunsce** [Geoxor/Xornet#75]
Adopt the  color/safe
```js
const colors = require('colors/safe');
console.log(colors.white("your msg here"));
```
over the current 
```js
require('colors');
console.log("your msg here".white);
```

**Comment by Geoxor** [comment]
whats the benifit of this?

**Comment by Bluskript** [comment]
Side effects are flimsy and unsafe. Generally considered bad practice in the JS world.

**Comment by Faunsce** [comment]
> 
> 
> Side effects are flimsy and unsafe. Generally considered bad practice in the JS world.

This is basically my reasoning, plus with the new logger, it just, should be used since the logger does and all non-logger printing will be rare so when it does happen its not so much to use the slightly longer but better way of stylization
